name: Master branch

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  code-scan:
    name: Code Scan
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: maven
      - name: Build with Maven and Coverage/Sonar
        run: mvn verify -P coverage,sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Codecov metrics
        uses: codecov/codecov-action@v3

  snapshots:
    name: Snaphots
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: OSSRH Snapshot
        run: mvn --batch-mode source:jar javadoc:jar deploy -Possrh -DskipTests

        env:
          MAVEN_USERNAME: ${{ secrets.nexus_username }}
          MAVEN_PASSWORD: ${{ secrets.nexus_password }}

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: maven
      - name: GitHub Snapshot
        run: mvn --batch-mode source:jar javadoc:jar deploy -Pgithub -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}
